version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: spamChecker_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresSpamChecker
      POSTGRES_DB: spamChecker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spamChecker_net

  app:
    build: .
    container_name: spamChecker_app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgresSpamChecker
      DB_NAME: spamChecker
      JWT_SECRET: SpamCheckerSuperSecret
    networks:
      - spamChecker_net

volumes:
  postgres_data:

networks:
  spamChecker_net:
    driver: bridge
